# Generated by Django 5.2.8 on 2025-11-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_body',
            field=models.TextField(blank=True, help_text='Request payload', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='request_headers',
            field=models.TextField(blank=True, help_text='JSON string of request headers', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='response_body',
            field=models.TextField(blank=True, help_text='Response content', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='response_headers',
            field=models.TextField(blank=True, help_text='JSON string of response headers', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='view_name',
            field=models.CharField(blank=True, help_text='Django view name/path', max_length=255, null=True),
        ),
    ]
